---
  - name: HACKING TOOLS | Create Tools directory
    win_file: 
      path: c:\Tools
      state: directory

  - name: HACKING TOOLS | Upload DownloadTools.ps1
    ansible.windows.win_copy:
      src: "files/DownloadTools.ps1"
      dest: "c:\\Tools\\DownloadTools.ps1"

  - name: HACKING TOOLS | Download Tools
    win_shell: c:\Tools\DownloadTools.ps1
    args:
      chdir: c:\Tools\

