---
- hosts: gohan
  gather_facts: True
  vars:
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
    capsulecorp_domain_hostname: "gohan"
    ethernet_adapter: "Ethernet"
    host_ip: "192.168.56.8"
  roles:
    - role: disable_rtm
    - role: activate_windows_srv
    - role: joindomain
    - role: mssql
    - role: windows_ip
