---
- hosts: goku
  gather_facts: True
  vars:
    dc_address: 172.28.128.100
    dc_netmask_cidr: 24
    dc_gateway: 172.28.128.2
    dc_hostname: goku
    domain_Name: capsulecorp.local
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
  tasks:
  - name: Activate windows
    win_shell: cscript slmgr.vbs /rearm
    args:
      chdir: C:\Windows\System32\

  - name: Set up static IP address
    win_shell: "Get-NetIpAddress -InterfaceAlias 'Ethernet' | New-NetIpAddress -IpAddress 172.27.109.5 -PrefixLength 20 -DefaultGateway 172.27.96.1"
    async: 100 # Using "fire-and-forget" asynchronous execution for this task, otherwise it will always fail and timeout
    poll: 0

  - name: Change ansible's ip address for each host
    set_fact:
      ansible_host: "172.27.109.5"

  - name: Wait for the hosts network interface to come back up
    local_action:
      module: wait_for
      host: "{{ ansible_host }}"
      port: 5985
      delay: 10
      state: started
    register: wait_result
  roles:
    - role: promotedc
