---
- hosts: pentest
  become: true
  gather_facts: True
  roles:
    - role: linux_static_ip
  tasks:    
  - name: Updated apt keys
    shell: wget --no-check-certificate https://http.kali.org/kali/pool/main/k/kali-archive-keyring/kali-archive-keyring_2022.1_all.deb -O /tmp/keyring_2022.deb; apt install -f /tmp/keyring_2022.deb

  - name: Remove "binutils" to avoid error dependencies
    ansible.builtin.apt:
      name: binutils
      state: absent

  - name: Install "python3-impacket" package
    ansible.builtin.apt:
      name: python3-impacket
      update_cache: yes

  - name: Install "remmina" package
    ansible.builtin.apt:
      name: remmina

  - name: Remove "light-locker" package
    ansible.builtin.apt:
      name: light-locker
      state: absent

  - name: Create user auditor
    shell: useradd -m auditor; usermod -aG adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,netdev,wireshark,bluetooth,scanner,kaboxer,docker auditor; chsh -s /bin/bash auditor

  - name: Change auditor password
    ansible.builtin.user:
      name: "auditor"
      state: present
      password: "$6$LbY1vAN9zLT1RUNA$CEe2wmcCx3r/mmq/96LgGXvK3vCQjFzT0RUjSZDOuetXwmJV01UPv4n0xoI0JJuGukxE6KC0F2kCNzfWazSyG0"

  - name: Reboot the machine
    reboot:
      reboot_timeout: 100