---
- hosts: raditz
  gather_facts: True
  vars:
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
    ethernet_adapter: "Ethernet"
    host_ip: "192.168.56.7"
    dns_server: "192.168.56.5"

  roles:
   - role: disable_rtm
   - role: activate_windows_srv
   - role: joindomain
   - role: unconstrained_delegation
   - role: windows_ip
   - role: local_admin_password
