---
- hosts: raditz
  gather_facts: True
  vars:
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
    capsulecorp_domain_hostname: "raditz"
    ethernet_adapter: "Ethernet"
    host_ip: "192.168.56.7"

  roles:
   - role: disable_rtm
   - role: activate_windows_srv
   - role: joindomain
   - role: unconstrained_delegation
   - role: windows_ip
