---
- hosts: raditz
  gather_facts: True
  vars:
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
    capsulecorp_domain_hostname: "raditz"
    ethernet_adapter: "Ethernet"
    anpt_flag: "flag3.txt" 
    host_ip: "192.168.56.7"
  tasks:
  - include_tasks: "./roles/activate_windows/tasks/windows_wks.yml"

  - name: Fix a host static IP after reboot
    community.windows.win_scheduled_task:
      name: TaskName2
      description: open command prompt
      actions:
      - path: cmd
        arguments: /c netsh interface ipv4 set address name="Ethernet" static {{host_ip}} 255.255.255.0 192.168.56.1
      triggers:
      - type: boot
      username: SYSTEM
      state: present
      enabled: yes

  - name: Activate windows
    win_shell: cscript slmgr.vbs /rearm
    args:
      chdir: C:\Windows\System32\
  roles:
   - role: disable_rtm
   - role: joindomain
   - role: unconstrained_delegation
#   - role: placeflag
