---
- hosts: raditz
  gather_facts: True
  vars:
    ansible_winrm_transport: plaintext
    ansible_winrm_scheme: http
    capsulecorp_domain_hostname: "raditz"
    ethernet_adapter: "Ethernet"
    anpt_flag: "flag3.txt"
  tasks:
  - name: Activate windows
    win_shell: cscript slmgr.vbs /rearm
    args:
      chdir: C:\Windows\System32\
  - win_feature:
      name: "web-server"
      state: present
      restart: yes
      include_sub_features: yes
      include_management_tools: yes
  roles:
   - role: disable_rtm
   - role: joindomain
   - role: unconstrained_delegation
#   - role: placeflag
