---
  - name: Kali | Create user auditor
    shell: useradd -m auditor; usermod -aG adm,dialout,cdrom,floppy,sudo,audio,dip,video,plugdev,netdev,wireshark,bluetooth,scanner,kaboxer auditor; chsh -s /bin/bash auditor
  
  - name: Kali | Change auditor password
    ansible.builtin.user:
      name: "auditor"
      state: present
      password: "$6$LbY1vAN9zLT1RUNA$CEe2wmcCx3r/mmq/96LgGXvK3vCQjFzT0RUjSZDOuetXwmJV01UPv4n0xoI0JJuGukxE6KC0F2kCNzfWazSyG0"

  - name: Kali | Updated apt keys
    shell: wget --no-check-certificate https://http.kali.org/kali/pool/main/k/kali-archive-keyring/kali-archive-keyring_2022.1_all.deb -O /tmp/keyring_2022.deb; apt install -f /tmp/keyring_2022.deb

  - name: Kali | Remove "binutils" to avoid error dependencies
    ansible.builtin.apt:
      name: binutils
      state: absent

  - name: Kali | Install "python3-impacket" package
    ansible.builtin.apt:
      name: python3-impacket
      update_cache: yes

  - name: Kali | Install "remmina" package
    ansible.builtin.apt:
      name: remmina

  - name: Kali | Install "Apache2" package
    ansible.builtin.apt:
      name: apache2

  - name: Kali | Update /var/www/htlm privileges
    ansible.builtin.file:
      path: /var/www/html
      group: auditor
      mode: u=rwx,g=rwx,o=r

  - name: Kali | Start service Apache2
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes

  - name: Kali | Install "samba" package
    ansible.builtin.apt:
      name: samba

  - name: Kali | Backup samba config file
    shell: cp /etc/samba/smb.conf /etc/samba/smb.conf.bak

  - name: Kali | Update samba config file
    template:
      src: "files/smb.conf"
      dest: "/etc/samba/smb.conf"

  - name: Kali | Start service Samba
    ansible.builtin.service:
      name: smbd
      state: started
      enabled: yes

  # - name: Kali | Upload xorg.conf to avoid errors during system upgrade Connection 1
  #   template:
  #     src: "files/xorg.conf"
  #     dest: "/etc/X11/xorg.conf.d/xorg.conf"

  - name: Kali | Upload install_xrdp.sh to execute after Kali dist-upgrade
    template:
      src: "files/install_xrdp.sh"
      dest: "/home/auditor/install_xrdp.sh"

  - name: Kali | Upload Interfaces
    template:
      src: "files/interfaces"
      dest: "/etc/network/interfaces"
      
  - name: Kali | Upload Wired Connection 1
    template:
      src: "files/WiredConnection1"
      dest: "/etc/NetworkManager/system-connections/Wired\ connection\ 1"

  - name: Kali | Reboot the machine
    reboot:
      reboot_timeout: 100