---
  - name: create a directory for the setup 
    win_file: 
      path: c:\setup
      state: directory

  - name: create a directory for setting up MSSQL
    win_file: 
      path: c:\setup\mssql
      state: directory

  - name: create a directory for MSSQL media extraction
    win_file: 
      path: c:\setup\mssql\media
      state: directory

  - name: Upload MSSQL Installer
    ansible.windows.win_copy:
      src: "files/SQL2019-SSEI-Expr.exe"
      dest: "c:\\setup\\mssql\\sql_installer.exe"

  - name: Upload MSSQL configuration file
    win_template: 
      src: files/sql_conf.ini.j2
      dest: c:\setup\mssql\sql_conf.ini

  - name: Install the database
    win_command: c:\setup\mssql\sql_installer.exe /configurationfile=c:\setup\mssql\sql_conf.ini /IACCEPTSQLSERVERLICENSETERMS /MEDIAPATH=c:\setup\mssql\media /QUIET /HIDEPROGRESSBAR
    args:
      chdir: c:\setup
    vars:
      ansible_become: yes
      ansible_become_method: runas
      ansible_become_user: "vagrant"
      ansible_become_password: "vagrant"
    register: mssqlinstall
    until: "mssqlinstall is not failed"
    retries: 1
    delay: 120

  - name: Add or update registry for MSSQL listening port
    win_regedit:
      path: 'HKLM:\Software\Microsoft\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQLServer\SuperSocketNetLib\Tcp\IPAll'
      name: TcpPort
      data: 1433
    register: win_reg

  - name: Restart a service
    win_service:
      name: 'MSSQL$SQLEXPRESS'
      force_dependent_services: yes
      state: restarted
    when: win_reg.changed

  - name: Firewall | Allow MSSQL through Firewall
    win_firewall_rule:
      name: Allow MSSQL through Firewall
      localport: 1433
      action: allow
      direction: in
      protocol: tcp
      state: present
      profile: "Domain"
      enabled: yes
      description: "Opens the listener port for MSSQL"


  - name: Firewall | Allow MSSQL discover through Firewall
    win_firewall_rule:
      name: "Access for MSSQL (UDP-In)"
      localport: 1434
      action: allow
      direction: in
      protocol: udp
      state: present
      profile: "Domain"
      enabled: yes
      description: "Opens the discover port for MSSQL"