---
  - name: ACCOUNTS | Ensure AD account sql_svc exists
    community.windows.win_domain_user:
      name: sql_svc
      firstname: sql_svc
      password: PassW0rd@MSSQL
      state: present
      groups:
        - Domain Users
      spn:
        - "MSSQLSvc/gohan.capsulecorp.local:1433"
        - "MSSQLSvc/gohan.capsulecorp.local"

  - name: ACCOUNTS | Add TrustedToAuthForDelegation to SQL_SVC 
    win_shell: Set-ADAccountControl -Identity 'sql_svc' -TrustedToAuthForDelegation $True

  - name: ACCOUNTS | Add msDS-AllowedToDelegateTo to SQL_SVC   
    win_shell: Set-ADUser -Identity "sql_svc" -Add @{'msDS-AllowedToDelegateTo'=@('CIFS/goku.capsulecorp.local','CIFS/GOKU')} 

  - name: ACCOUNTS | Ensure AD account iis_svc exists
    win_domain_user:
      name: iis_svc
      firstname: iis_svc
      password: p@$$w0rd
      state: present
      groups:
        - Domain Users
      spn:
        - "IISSvc/raditz.capsulecorp.local:1433"
        - "IISLSvc/raditz.capsulecorp.local"

  - name: ACCOUNTS | Ensure AD account vuln_svc exists
    win_domain_user:
      name: vuln_svc
      firstname: vuln_svc
      password: PassW0rd@SVC
      state: present
      groups:
        - Domain Users

  - name: ACCOUNTS | Ensure AD account serveradmin exists
    win_domain_user:
      name: server.admin
      firstname: ServerAdmin
      password: P@ssW0rd432!
      state: present
      groups:
        - Domain Admins

  - name: ACCOUNTS | Ensure AD account User1 exists
    community.windows.win_domain_user:
      name: employee1
      firstname: employee1
      password: PassW0rd!
      state: present
      groups:
        - Domain Users