---
  - name: Upload Script
    template:
      src: "vulnadplus.ps1"
      dest: "C:\\vulnadplus.ps1"
    register: script_placed

  - name: Run Vulnerable-AD Script
    win_shell: Import-module C:\\vulnadplus.ps1; Invoke-VulnAD -UsersLimit 10 -DomainName "capsulecorp.local"

  - name: Reboot server after Vulnerable-AD Script
    win_reboot:
      test_command: 'exit (Get-Service -Name LanmanServer).Status -ne "Running"'
    when: domain_create.reboot_required