# This is the network config written by 'subiquity'
network:
  ethernets:
    eth0:
      addresses:
        - 10.10.10.2/24
      nameservers:
        addresses: [10.10.10.1]
      routes:
        - to: default
          via: 10.10.10.1
      dhcp4: true
      dhcp6: false
  version: 2