---
- name: Point dns to Goku
  win_dns_client:
    adapter_names: "{{ ethernet_adapter }}"
    ipv4_addresses:
      - 172.23.66.146
      - 8.8.8.8
  register: dns_setup

# Make sure RDP is on
- include_tasks: enable_rdp.yml

#  Setup the firewall
- include_tasks: firewall_445.yml

- include_tasks: firewall_3389.yml

# Disable Real Time Monitoring
- include_tasks: disable_rtm.yml

- name: Join the capsulecorp.local domain
  win_domain_membership:
    dns_domain_name: capsulecorp.local
    hostname: "{{ capsulecorp_domain_hostname }}"
    domain_admin_user: goku@capsulecorp.local
    domain_admin_password: PassW0rd432!
    state: domain
  register: domain_state

- name: Install ActiveDirectory Module
  win_shell: "Add-WindowsFeature RSAT-AD-PowerShell"

- name: Reboot the server
  raw: shutdown /r

- name: Wait for the host to come back up
  local_action:
    module: wait_for
    host: "{{ ansible_host }}"
    port: 5985
    delay: 10
    state: started
  register: wait_result