---
- name: Point dns to Goku
  win_dns_client:
    adapter_names: "{{ ethernet_adapter }}"
    ipv4_addresses:
      - 172.28.216.36
      - 1.1.1.1
  register: dns_setup

# Make sure RDP is on
- include_tasks: enable_rdp.yml

#  Setup the firewall
- include_tasks: firewall_445.yml

- include_tasks: firewall_3389.yml

- name: Install ActiveDirectory Module
  win_shell: "Add-WindowsFeature RSAT-AD-PowerShell"

- name: Join the capsulecorp.local domain
  win_domain_membership:
    dns_domain_name: capsulecorp.local
    domain_admin_user: Administrator@capsulecorp.local
    domain_admin_password: PassW0rd432!
    state: domain
  register: domain_state

- name: Reboot if needed
  win_reboot:    
    reboot_timeout: 1500
    post_reboot_delay: 100
  when: domain_state.reboot_required
